import bcrypt from 'bcrypt';

import { prisma } from '../src/db/prisma';
import { seedExampleRecommendationsForUser } from '../src/modules/recommendations/recommendations.service';

const EMAIL = process.env.SEED_EMAIL ?? 'demo@timeflow.local';
const PASSWORD = process.env.SEED_PASSWORD ?? 'Password123!';
const TASKS_TO_CREATE = Number(process.env.SEED_TASKS ?? 25);

function dueInHours(hours: number): Date {
  return new Date(Date.now() + hours * 60 * 60 * 1000);
}

function dueHoursAgo(hours: number): Date {
  return new Date(Date.now() - hours * 60 * 60 * 1000);
}

async function ensureDemoUser(): Promise<{ id: string; email: string }> {
  const existing = await prisma.user.findUnique({
    where: { email: EMAIL },
    select: { id: true, email: true },
  });
  if (existing !== null) {
    console.log(`[seed] user already exists: ${EMAIL}`);
    return existing;
  }

  const passwordHash = await bcrypt.hash(PASSWORD, 12);
  const user = await prisma.user.create({
    data: { email: EMAIL, name: 'Demo User', passwordHash },
    select: { id: true, email: true },
  });
  console.log(`[seed] created user ${user.email}`);
  return user;
}

async function demoUserHasSeedData(userId: string): Promise<boolean> {
  const count = await prisma.task.count({
    where: { userId, description: 'generated by seed-demo' },
  });
  return count > 0;
}

async function seedTasks(userId: string): Promise<string[]> {
  const ids: string[] = [];

  for (let i = 0; i < TASKS_TO_CREATE; i += 1) {
    const isOverdueSample = i >= TASKS_TO_CREATE - 3;
    const dueAt = isOverdueSample
      ? dueHoursAgo(2 + (TASKS_TO_CREATE - i))
      : dueInHours(6 + (i % 10));
    const task = await prisma.task.create({
      data: {
        userId,
        title: `Seed Task ${i + 1}`,
        description: 'generated by seed-demo',
        dueAt,
        status: 'PENDING',
      },
      select: { id: true },
    });
    ids.push(task.id);
  }

  return ids;
}

async function main(): Promise<void> {
  console.log(`[seed] email=${EMAIL} tasks=${TASKS_TO_CREATE}`);

  const user = await ensureDemoUser();
  const hasSeedData = await demoUserHasSeedData(user.id);

  if (hasSeedData) {
    console.log(`[seed] demo data already exists for ${EMAIL}, refreshing recommendations only`);
  } else {
    const taskIds = await seedTasks(user.id);
    console.log(`[seed] created tasks=${taskIds.length}`);

    const doneCount = Math.max(1, Math.floor(taskIds.length * 0.4));
    const cancelCount = Math.max(0, Math.floor(taskIds.length * 0.1));

    for (let i = 0; i < doneCount; i += 1) {
      await prisma.task.update({
        where: { id: taskIds[i] },
        data: { status: 'DONE' },
      });
    }

    for (let i = doneCount; i < doneCount + cancelCount; i += 1) {
      await prisma.task.update({
        where: { id: taskIds[i] },
        data: { status: 'CANCELED' },
      });
    }

    console.log(`[seed] done=${doneCount} canceled=${cancelCount}`);
  }

  const recommendationCount = await seedExampleRecommendationsForUser(user.id, new Date());
  console.log(`[seed] example recommendations=${recommendationCount}`);
  console.log('[seed] OK - demo user ready (login with SEED_EMAIL / SEED_PASSWORD; other users unchanged)');
}

main()
  .catch((err: unknown) => {
    const message = err instanceof Error ? err.message : String(err);
    console.error('[seed] failed:', message);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
